{% set version = "0.0.3" %}

package:
  name: geojsonio
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/geojsonio/geojsonio-{{ version }}.tar.gz
  sha256: 2afe91d9a86e30aaf0c449f430a024ab03503db3efce2e26ff5f1057f32f1083

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - geojsonio = geojsonio:main


requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - github3.py
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - geojsonio
  commands:
    - geojsonio --help

about:
  home: https://github.com/jwass/geojsonio.py
  license: BSD 3-Clause
  summary: 'geojsonio CLI - Python.'

extra:
  recipe-maintainers:
    - ocefpaf
